### PR TITLE
Add recipient type

### PR DESCRIPTION
**Pull request by leominov**

### CODE REVIEW

**Comment by Azelphur** [comment]
"add recipient type" is a reasonably good change, it would be a minor API break but also follow the pushbullet API better so I'd accept that change

However, why have you just deleted the command line client?

**Comment by leominov** [comment]
May be right place of examples in documentation.

**Comment by Azelphur** [comment]
No, people use it. Lots of software supports running a command on an event (eg torrent clients firing an event for a download completed). It's not an example, it's part of the project.

**Comment by leominov** [comment]
Oh, right, my fault.

**Comment by Azelphur** [comment]
Haha no problem, I cherry picked add recipient type. It's all merged now. Thanks for your contribution :)

**Comment by leominov** [comment]
Thank you!)

**Pull request closed without merging**
